### ISSUE TITLE
Question about the performance of DDPM-based methods.

### ISSUE THREAD

**Issue by mileswyn** [caiyu6666/MedIAnomaly#2]
Thanks for your great work!
I wonder if you conducted some comparisons on this benchmark with some ddpm-based methods?
And if you did it, could you share some experiences which kind of methods show SOTA performance on the MedIAnomaly benchmark?
Hope for your reply!

**Comment by caiyu6666** [comment]
Thanks for your attention!
We intend to investigate the DDPM-based methods later and add these contents at the revision stage. 
Before that, you might take the dataloaders from 
'./reconstruction/dataloaders/` to run your interested methods on these datasets for comparison.

**Comment by caiyu6666** [comment]
Hi. We have included two DDPM-based methods, AnoDDPM and AutoDDPM, in our experiments.
Please check the updated manuscript at https://arxiv.org/abs/2404.04518.
Hope these results are useful for you!
