### ISSUE TITLE
Data processig

### ISSUE THREAD

**Issue by RNZZL** [caiyu6666/MedIAnomaly#3]
Thank you for your excellent work!

Could you please share the data processing code for VinDr-CXR? It seems the bounding boxes are not aligned with the resized images.

Looking forward to your response!

**Comment by caiyu6666** [comment]
Hi~
The reason is that VinDr-CXR provides the bbox annotation with absolute coordinates on original images. Your may check the original size of images in [their official website](https://www.kaggle.com/c/vinbigdata-chest-xray-abnormalities-detection/data), then reference to the code below for drawing the bbox:
```python
IMAGE_ID = "your_image_id"
x0, y0 = 2405, 2716  # the height and width of the original image [IMAGE_ID]. 
# Please note that the resolution may be different across images. 

img_path = os.path.join(data_path, 'images', "[IMAGE_ID].png").  # The provided processed images
img = cv2.imread(img_path). 
anno = data_csv[data_csv['image_id']==IMAGE_ID].iloc[:, -4:]

for index, x in anno.iterrows():
    x_min, y_min, x_max, y_max = x
    x_min, x_max = x_min/x0 * 512, x_max/x0 * 512
    y_min, y_max = y_min/y0 * 512, y_max/y0 * 512

    x_min, y_min, x_max, y_max = int(x_min), int(y_min), int(x_max), int(y_max)
    cv2.rectangle(img, (x_min, y_min), (x_max, y_max), (0, 0, 255), 2)
cv2.imwrite("output.png", img)
```

**Comment by caiyu6666** [comment]
The data processing code for these datasets is available at https://github.com/caiyu6666/DDAD-ASR/tree/main/data

**Comment by RNZZL** [comment]
Thank you for the helpful clarification
