### ISSUE TITLE
Is this paper published in Medical Image Analysis 2024 ?

### ISSUE THREAD

**Issue by op1009** [caiyu6666/MedIAnomaly#4]
Thanks for doing this detailed comparative study!
The paper is bound to be very helpful for everyone doing work in this area. 

The pre-print available on arXiv [https://arxiv.org/pdf/2404.04518](https://arxiv.org/pdf/2404.04518) shows that this paper is published in Medical Image Analysis, but I couldn't find the original version from science direct. 

Please help me find the original MIA 2024 link.

Is it still in pre-print ?

**Comment by caiyu6666** [comment]
Hi. This manuscript is still under submission, as indicated by the comments on https://arxiv.org/abs/2404.04518. Sorry for any confusion caused by the template.

**Comment by op1009** [comment]
my bad ... I should have checked comments.
Thanks for clarification :+1:
