### ISSUE TITLE
Could the author share the code for the visualization part？

### ISSUE THREAD

**Issue by hanli6688** [caiyu6666/MedIAnomaly#5]
Could the author share the code for the visualization part？

**Comment by caiyu6666** [comment]
Hi. The code for visualization is available at https://github.com/caiyu6666/MedIAnomaly/blob/main/reconstruction/utils/ae_worker.py#L161

**Comment by hanli6688** [comment]
> Hi. The code for visualization is available at https://github.com/caiyu6666/MedIAnomaly/blob/main/reconstruction/utils/ae_worker.py#L161

thank you very much！
